#CV DL

In [ ]:
import numpy as np

In [ ]:
y_actual = np.array([0.30, 0.7,1,0, 0.5])
y_predicted = np.array([1, 1, 0, 0 ,1])

In [ ]:
y_actual

array([0.3, 0.7, 1. , 0. , 0.5])

In [ ]:
y_predicted

array([1, 1, 0, 0, 1])

#1. Mean Squared Error (MSE)

In [ ]:
def mse(y_actual,y_predicted):
  total_error = 0
  for ya, yp in zip(y_actual, y_predicted): #zip function will help in iterating two differnt iterators in a single for loop
    total_error +=  (ya -yp)**2
  print("Total error is", total_error)
  mse = total_error / len(y_actual)
  print("MSE is", mse)


In [ ]:
# calling function

mse(y_actual, y_predicted)


Total error is 1.83
MSE is 0.366


#2. Mean Absolute Error

In [ ]:
def mae(y_actual,y_predicted):
  total_error = 0
  for ya, yp in zip(y_actual, y_predicted): #zip function will help in iterating two differnt iterators in a single for loop
    total_error +=  abs(ya -yp)
  print("Total error is", total_error)
  mae = total_error / len(y_actual)
  print("MAE is", mae)

In [ ]:
mae(y_actual, y_predicted)

Total error is 2.5
MAE is 0.5


#3. Log Loss

Since log(0) is not defined we cant put y_pred as 0 or 1 ...so we will replace 0 with 0.0000001 which is close to zero and 1 with 0.999999

In [ ]:
y_predicted

array([1, 1, 0, 0, 1])

In [ ]:
np.log([0]) #log 0 not defined

<ipython-input-11-faee82fd9f21>:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [ ]:
epsilon = 1e-15    #e^-15 = 1/2.71^-15 = very small value close to zero
print(epsilon)

1e-15


In [ ]:
np.log(epsilon)

-34.538776394910684

In [ ]:
#so we will replace our zero with epsilon

In [ ]:
y_pred_new = [max(i, epsilon) for i in y_predicted]
y_pred_new

#For each element i, it returns the maximum of i and epsilon. This ensures that if i is less than epsilon, it is replaced with epsilon

[1, 1, 1e-15, 1e-15, 1]

next task to replace 1 with 0.99999

In [ ]:
y_pred_new =np.array([min(i, 1-epsilon) for i in y_pred_new])
y_pred_new

array([1.e+00, 1.e+00, 1.e-15, 1.e-15, 1.e+00])

now are values are ready to feed in logloss equstion

In [ ]:
-np.mean(y_actual* np.log(y_pred_new) + (1 - y_actual)* np.log(1- y_pred_new))

17.2696280766844

#now we will put everything inside the function

In [ ]:
def logloss(y_actual, y_predicted):
  y_pred_new = [max(i , epsilon) for i in y_predicted]
  y_pred_new = [min(i , 1-epsilon)for i in y_pred_new]
  y_pred_new = np.array(y_pred_new)
  return -np.mean(y_actual * np.log(y_pred_new) + (1-y_actual) * np.log(1 - y_pred_new))

In [ ]:
#calling the function
logloss(y_actual, y_predicted)

17.2696280766844